module.exports = {
  prefix: "",
  important: true,
  theme: {
    container: {
      center: true,
    },
    fontFamily: {},
    screens: {
      mobile: "0px",
      lanscape: "640px",
      tablet: "768px",
      desktop: "1024px",
      ultradesktop: "1280px",
    },
    colors: {},
    backgroundColor: (theme) => theme("colors"),
    spacing: {},
    fontSize: {},
    fontWeight: {
      hairline: "100",
      thin: "200",
      light: "300",
      normal: "400",
      medium: "500",
      semibold: "600",
      bold: "700",
      extrabold: "800",
      black: "900",
    },
    backgroundSize: {
      auto: "auto",
      cover: "cover",
      contain: "contain",
    },
    borderColor: (theme) => theme("colors"),
    textColor: (theme) => theme("colors"),
    placeholderColor: (theme) => theme("colors"),
    opacity: {
      "0": "0",
      "25": "0.25",
      "50": "0.50",
      "75": "0.75",
      "100": "1",
    },
  },
  variants: {},
  plugins: [],
};
